// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWdc4PQWBsHwdZt2FXZAK3IwkvrrC6rDk',
    appId: '1:98902394498:web:7eab40f698baeeadfd169b',
    messagingSenderId: '98902394498',
    projectId: 'shop-easy-ff939',
    authDomain: 'shop-easy-ff939.firebaseapp.com',
    storageBucket: 'shop-easy-ff939.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7sZGOtL3UWvJIZWkCtN_n6LDZhjEMBQ0',
    appId: '1:98902394498:ios:80b939f44d3aaee0fd169b',
    messagingSenderId: '98902394498',
    projectId: 'shop-easy-ff939',
    storageBucket: 'shop-easy-ff939.appspot.com',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWdc4PQWBsHwdZt2FXZAK3IwkvrrC6rDk',
    appId: '1:98902394498:web:9ee6082fa8006c8efd169b',
    messagingSenderId: '98902394498',
    projectId: 'shop-easy-ff939',
    authDomain: 'shop-easy-ff939.firebaseapp.com',
    storageBucket: 'shop-easy-ff939.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7sZGOtL3UWvJIZWkCtN_n6LDZhjEMBQ0',
    appId: '1:98902394498:ios:80b939f44d3aaee0fd169b',
    messagingSenderId: '98902394498',
    projectId: 'shop-easy-ff939',
    storageBucket: 'shop-easy-ff939.appspot.com',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_oc6WU0TI373jwWZfIWi9uqBZyyAPWKM',
    appId: '1:98902394498:android:b54f7819d3a2e05ffd169b',
    messagingSenderId: '98902394498',
    projectId: 'shop-easy-ff939',
    storageBucket: 'shop-easy-ff939.appspot.com',
  );

}