// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjgQDVa0Vy8lZEEFKmsAhhvTVOZLpsP3Q',
    appId: '1:713835835115:web:42ef41966874a57e1858ae',
    messagingSenderId: '713835835115',
    projectId: 'shopeasy-4bddf',
    authDomain: 'shopeasy-4bddf.firebaseapp.com',
    storageBucket: 'shopeasy-4bddf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZcm0qFuH_dUd5DBKsDXBIG7tvgIDGwR8',
    appId: '1:713835835115:android:dc9307a5bcb111011858ae',
    messagingSenderId: '713835835115',
    projectId: 'shopeasy-4bddf',
    storageBucket: 'shopeasy-4bddf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWeJzEy1zitJtceDnPikgk4juYxQpDWQE',
    appId: '1:713835835115:ios:5d5337da083bd0191858ae',
    messagingSenderId: '713835835115',
    projectId: 'shopeasy-4bddf',
    storageBucket: 'shopeasy-4bddf.appspot.com',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWeJzEy1zitJtceDnPikgk4juYxQpDWQE',
    appId: '1:713835835115:ios:5d5337da083bd0191858ae',
    messagingSenderId: '713835835115',
    projectId: 'shopeasy-4bddf',
    storageBucket: 'shopeasy-4bddf.appspot.com',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjgQDVa0Vy8lZEEFKmsAhhvTVOZLpsP3Q',
    appId: '1:713835835115:web:7fbf777a699bad851858ae',
    messagingSenderId: '713835835115',
    projectId: 'shopeasy-4bddf',
    authDomain: 'shopeasy-4bddf.firebaseapp.com',
    storageBucket: 'shopeasy-4bddf.appspot.com',
  );

}